# Source: https://github.com/lowlighter/metrics/blob/master/action.yml
name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          user: pablomatiasgomez
          template: classic
          base: header, activity, community, repositories, metadata
          config_display: large
          config_timezone: America/Buenos_Aires

          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: data, markup, programming, prose
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: data, markup, programming, prose
          plugin_languages_recent_days: 90
          plugin_languages_recent_load: 1000
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%

          plugin_lines: yes
          plugin_lines_sections: base, repositories, history